export const genreData = [
  'Architecture',
  'Art & Fashion',
  'Biography',
  'Business',
  'Crafts & Hobbies',
  'Drama',
  'Fiction',
  'Food & Drink',
  'Health & Wellbeing',
  'History & Politics',
  'Humor',
  'Poetry',
  'Psychology',
  'Science',
  'Technology',
  'Travel & Maps',
];